inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Guardfile
    - app/helpers/items_helper.rb
    - local/**/*

Metrics/LineLength:
  Max: 100
Documentation:
    Enabled: false
Lint/EndAlignment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 28

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 9

Style/AccessorMethodName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false