inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Guardfile
    - app/helpers/items_helper.rb
    - local/**/*
    
Documentation:
    Enabled: false
Lint/EndAlignment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes