language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - 2.3.0
env:
  - RAILS_ENV=test
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec
services:
  - postgresql
before_script:
  - psql -c 'create database ruvoin_test;' -U postgres