# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5321b7e7e71b640f1683ab3710518a0ad581a592e155682e13a73cc706aaf1a23e344dab1126a139b5ed8dac550b3c5e61fb1d044e3f1dc0f04f9b468dd5bca8

test:
  secret_key_base: 055b5d8dbc71d11bf506769e0f4d56cbbd0194f61dd3b2b219dc0f0f163adec8d22f2901b557766658f874fe0734cb675e4c219344825b85a808207e90f02d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
